# Generated by Django 3.2.4 on 2021-06-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Improve', 'Improve'), ('Task', 'Task')], default='Task', max_length=10),
        ),
    ]
