# Generated by Django 3.2.4 on 2021-07-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_auto_20210706_1114"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="author",
            new_name="author",
        ),
    ]
