# Generated by Django 3.2.4 on 2021-07-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_rename_author_user_issue_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
    ]
