# Generated by Django 3.2.4 on 2021-07-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_rename_assignee_issue_assignee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
    ]
