# Generated by Django 3.2.4 on 2021-07-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_alter_issue_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee',
            new_name='assignee_user_id',
        ),
    ]
