# Generated by Django 3.2.4 on 2021-09-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0017_alter_issue_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user',
            new_name='assignee',
        ),
    ]
