# Generated by Django 3.2.4 on 2021-09-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0014_remove_contributor_permission'),
        ('issues', '0023_alter_issue_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to='contributors.contributor'),
        ),
    ]
