# Generated by Django 3.2.4 on 2021-06-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_auto_20210621_1706"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_user_id",
            new_name="author",
        ),
    ]
