# Generated by Django 3.2.4 on 2021-07-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_rename_issue_id_comment_issue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="author",
        ),
    ]
