# Generated by Django 3.2.4 on 2021-06-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0002_alter_contributor_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributor",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="contributor",
            old_name="username_id",
            new_name="user",
        ),
    ]
