# Generated by Django 3.2.4 on 2021-07-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20210622_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='author_user',
        ),
    ]
