# Generated by Django 3.2.4 on 2021-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_rename_user_contributor_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Read', 'Read')], default='Read', max_length=7),
        ),
    ]
