# Generated by Django 3.2.4 on 2021-07-08 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contributors", "0008_alter_contributor_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="username",
        ),
        migrations.AddField(
            model_name="contributor",
            name="username_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
