# Generated by Django 3.2.4 on 2021-07-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0009_auto_20210708_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='username_id',
            new_name='username',
        ),
    ]
