# Generated by Django 3.2.4 on 2021-07-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0010_rename_username_id_contributor_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='username',
            new_name='username_id',
        ),
    ]
