# Generated by Django 3.2.4 on 2021-09-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0013_rename_username_id_contributor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
    ]
